AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model (Check Keras Documentatation)
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1 # Training for 1 epoch
CLASSES: 2 # Coccidiosis OR Healthy
WEIGHTS: imagenet # Pr-trained weights (after training the model on "imagenet" dataset)
LEARNING_RATE: 0.01